name: Node CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 16

      - name: Install Dependencies
        run: |
          npm ci
          cd website
          npm ci

      - name: Lint Project
        run: npm run lint

      - name: Check Links
        run: npm run check-links

      - name: Test Project
        run: npm run test:coverage

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

      - name: Build Project
        run: npm run build

      - name: Build Website
        run: |
          cd website
          npm run build
